### ISSUE TITLE
Update to next.js

### ISSUE THREAD

**Issue by dpeachpeach** [GeoDaCenter/data-and-lab#43]
an update of the data-and-lab website to a more modern implementation utilizing next.js. 
Still utilizing a similar blog structure

**Comment by lixun910** [comment]
Thanks, David! One note: please get this pull request done first: https://github.com/GeoDaCenter/data-and-lab/pull/42 So we have kepler.gl map running in our existing site: https://geodacenter.github.io/data-and-lab/
