### ISSUE TITLE
Aug 3 Rendering Issues

### ISSUE THREAD

**Issue by dpeachpeach** [GeoDaCenter/data-and-lab#44]
- Fix styling issues with the Map size
- Fix styling issues w/ Map contents
- Update react components on react-geoda (Take a look at mouse hover state and change behavior of the map based on that)

- Write either a deploy or a bash script to clean up auto-generated IDs so that deployment is more automated.

**Comment by lixun910** [comment]
Thanks, David @dpeachpeach ! Maybe we can disable the hash ids in the file name, see https://stackoverflow.com/questions/73517245/how-to-remove-contenthash-hash-from-name-of-js-and-css-files

> Write either a deploy or a bash script to clean up auto-generated IDs so that deployment is more automated.

**Comment by dpeachpeach** [comment]
Hey @lixun910, I saw you seem to have taken care of disabling the hash-ids in https://github.com/GeoDaCenter/reactgeoda/pull/36#event-10013203294. Just confirming that.

**Comment by lixun910** [comment]
> Hey @lixun910, I saw you seem to have taken care of disabling the hash-ids in [GeoDaCenter/reactgeoda#36 (comment)](https://github.com/GeoDaCenter/reactgeoda/pull/36#event-10013203294). Just confirming that.

Yes, it has been taken care of. You can `git pull` under the reactgeoda folder to update the reactgeoda submodule.
